name: Build macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-apple-darwin,x86_64-apple-darwin
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build for Apple Silicon
      run: npm run tauri build -- --target aarch64-apple-darwin
    
    - name: Build for Intel Mac
      run: npm run tauri build -- --target x86_64-apple-darwin
    
    - name: Upload Apple Silicon artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-apple-silicon
        path: |
          src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
          src-tauri/target/aarch64-apple-darwin/release/bundle/macos/*.app
    
    - name: Upload Intel Mac artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-intel
        path: |
          src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/*.dmg
          src-tauri/target/x86_64-apple-darwin/release/bundle/macos/*.app