name: Release Build
on:
  push:
    tags: ['v*']

jobs:
  build-tauri:
    strategy:
      matrix:
        platform: [ubuntu-20.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Build Tauri App
        run: npm run tauri build
      - name: Code Sign (Windows/macOS)
        run: # Plattform-spezifische Signierung
      - name: Create Installer
        run: NSIS (Windows), DMG (macOS), AppImage (Linux)